### ISSUE TITLE
Please get in touch

### ISSUE THREAD

**Issue by klausagnoletti** [funkolab/cs-mikrotik-bouncer#12]
Hey - I love your work! I am head of community at CrowdSec. There's a few other initiatives in motion regarding MikroTik so could you please reach out to me at klaus@crowdsec.net or on our Discord - https://discord.gg/crowdsec so you guys can join forces?

Thanks a lot!

**Comment by jlgore** [comment]
Hello! @klausagnoletti pointed me here.  I love what you've done. Great job. This is something I have hacked on in the previous year but your repo is much cleaner. I have some hacky 7.X REST api bouncer that I haven't been able to work on all that much. If you have need for any help let me know.  I am down to collaborate or help.

**Comment by tuxtof** [comment]
Thanks @jlgore you are welcome
